version: '3.1'

services:

  redmine:
    build:
      context: .
    restart: always
    ports:
      - 10080:3000
    volumes:
      - ~/var/redmine/files:/usr/src/redmine/files
      - /usr/src/redmine
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: PASSWORD

  db:
    image: mysql:5.7
    # これを入れないと日本語が使えずあちこちでエラーが出る。
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ~/var/redmine/db/conf:/etc/mysql/conf.d
      - ~/var/redmine/db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: redmine
      TZ: JST-9